/* tslint:disable */
/* eslint-disable */
/**
 * Profile Service API
 * Profile Service api definitie
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
} from './Address';

/**
 * 
 * @export
 * @interface RomanticDate
 */
export interface RomanticDate {
    /**
     * 
     * @type {Address}
     * @memberof RomanticDate
     */
    address?: Address;
    /**
     * 
     * @type {Date}
     * @memberof RomanticDate
     */
    time?: Date;
    /**
     * 
     * @type {string}
     * @memberof RomanticDate
     */
    itemToBring?: string;
}

/**
 * Check if a given object implements the RomanticDate interface.
 */
export function instanceOfRomanticDate(value: object): value is RomanticDate {
    return true;
}

export function RomanticDateFromJSON(json: any): RomanticDate {
    return RomanticDateFromJSONTyped(json, false);
}

export function RomanticDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RomanticDate {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'itemToBring': json['itemToBring'] == null ? undefined : json['itemToBring'],
    };
}

export function RomanticDateToJSON(value?: RomanticDate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': AddressToJSON(value['address']),
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'itemToBring': value['itemToBring'],
    };
}

