CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street VARCHAR(255),
    street_number VARCHAR(255),
    postal_code VARCHAR(255),
    city VARCHAR(255),
    valid BOOLEAN NOT NULL DEFAULT FALSE,
    longitude NUMERIC(11, 8),
    latitude NUMERIC(10, 8)
);

CREATE TABLE personal_information (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    gender VARCHAR(255),
    favorite_color VARCHAR(255),
    pets BOOLEAN NOT NULL DEFAULT FALSE,
    hair_color VARCHAR(255),
    tattoos BOOLEAN NOT NULL DEFAULT FALSE,
    sports VARCHAR(255),
    music_genres VARCHAR(255)
);

CREATE TABLE preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    gender VARCHAR(255),
    favorite_color VARCHAR(255),
    pets BOOLEAN NOT NULL DEFAULT FALSE,
    hair_color VARCHAR(255),
    tattoos BOOLEAN NOT NULL DEFAULT FALSE,
    sports VARCHAR(255),
    music_genres VARCHAR(255)
);

CREATE TABLE dislikes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    gender VARCHAR(255),
    favorite_color VARCHAR(255),
    pets BOOLEAN NOT NULL DEFAULT FALSE,
    hair_color VARCHAR(255),
    tattoos BOOLEAN NOT NULL DEFAULT FALSE,
    sports VARCHAR(255),
    music_genres VARCHAR(255)
);

CREATE TABLE profile_date (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_street VARCHAR(255),
    address_street_number VARCHAR(255),
    address_postal_code VARCHAR(255),
    address_city VARCHAR(255),
    date_time TIMESTAMP WITH TIME ZONE,
    item_to_bring VARCHAR(255)
);

CREATE TABLE profile (
    username VARCHAR(255) PRIMARY KEY,
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    additional_info VARCHAR(255),
    address_id BIGINT,
    personal_information_id BIGINT,
    preferences_id BIGINT,
    dislikes_id BIGINT,
    CONSTRAINT fk_profile_address FOREIGN KEY (address_id) REFERENCES address (id),
    CONSTRAINT fk_profile_personal_information FOREIGN KEY (personal_information_id) REFERENCES personal_information (id),
    CONSTRAINT fk_profile_preferences FOREIGN KEY (preferences_id) REFERENCES preferences (id),
    CONSTRAINT fk_profile_dislikes FOREIGN KEY (dislikes_id) REFERENCES dislikes (id),
    CONSTRAINT uk_profile_address UNIQUE (address_id),
    CONSTRAINT uk_profile_personal_information UNIQUE (personal_information_id),
    CONSTRAINT uk_profile_preferences UNIQUE (preferences_id),
    CONSTRAINT uk_profile_dislikes UNIQUE (dislikes_id)
);

CREATE TABLE profile_dates (
    profile_username VARCHAR(255) NOT NULL,
    date_id BIGINT NOT NULL,
    CONSTRAINT fk_profile_dates_profile FOREIGN KEY (profile_username) REFERENCES profile (username) ON DELETE CASCADE,
    CONSTRAINT fk_profile_dates_date FOREIGN KEY (date_id) REFERENCES profile_date (id) ON DELETE CASCADE,
    CONSTRAINT uk_profile_dates_date UNIQUE (date_id)
);

CREATE INDEX idx_profile_dates_profile_username ON profile_dates (profile_username);
