spring:
  kafka:
    bootstrap-servers: localhost:9092
    group-id: date
  jackson:
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 9083
  error:
    include-message: always

endpoints:
  profileservice: http://localhost:9080
  locationservice: http://localhost:9084

logging:
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'