openapi: 3.0.1
info:
  title: Location Service API
  description: 'Location Service api definitie'
  version: 1.0.0
paths:
  /location:
    post:
      tags:
        - locations
      operationId: retrieveLocation
      description: haal coordinates op van locatie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        "404":
          $ref: '#/components/responses/NotFoundResponse'

components:
  responses:
    NotFoundResponse:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ConflictResponse:
      description: Resource already exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ErrorResponse:
      type: object
      properties:
        type:
          type: string
          description: a URI identifier that categorizes the error
        title:
          type: string
          description: a brief, human-readable message about the error
        status:
          type: integer
          description: the HTTP response code (optional)
        detail:
          type: string
          description: a human-readable explanation of the error
        instance:
          type: string
          description: a URI that identifies the specific occurrence of the error
        errors:
          type: array
          items:
            $ref: '#/components/schemas/FieldError'
    FieldError:
      type: object
      properties:
        field:
          type: string
          description: the field that the error is thrown on
        error:
          type: string
          description: the error message

    Address:
      type: object
      properties:
        street:
          type: string
        streetNumber:
          type: string
        postalCode:
          type: string
        city:
          type: string
        valid:
          type: boolean
        longitude:
          type: number
        latitude:
          type: number