spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
  jackson:
    default-property-inclusion: non_null
    serialization.FAIL_ON_EMPTY_BEANS: false
server:
  port: 9081
  error:
    include-message: always
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    path: /
    url: /profiles.yaml
    supportedSubmitMethods: []

endpoints:
  profileservice: http://localhost:9080

logging:
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'