name: blinddatingapp frontend CI

on:
  push:
    paths:
      - 'blinddatingapp-frontend/**'
      - '.github/workflows/blinddatingapp-frontend.yml'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and containerize with Jib
        run: |
          docker build -f blinddatingapp-frontend/Dockerfile -t docker.io/finkingma/blinddatingapp-frontend:latest .
          docker push docker.io/finkingma/blinddatingapp-frontend:latest