name: websocket service CI

on:
  push:
    paths:
      - 'websocket-service/**'
      - '.github/workflows/websocket-service.yml'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Build and containerize with Jib
        working-directory: ./websocket-service
        run: mvn clean compile jib:build

      - name: Deploy websocket to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: websocket-service
          token: ${{ secrets.CAPROVER_WEBSOCKET_TOKEN }}
          image: docker.io/finkingma/websocket-service:latest
